server:
  port: 8080

grpc:
  port: 9090

logging:
  config: classpath:logback.xml

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/sqlite/sqlite.db

mybatis:
  mapper-locations: classpath:mapper/*.xml

