version: '2'

services:
  music-api:
    image: music-api:latest
    container_name: music-api
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    - music-api-data:/music/data
    ports:
    - '8080:9090'

volumes:
  music-api-data: {}